apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs2
    app.kubernetes.io/part-of: scenario2
  name: nodejs2
  namespace: erikmjacobs
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs2
    weight: 100
status: {}
